### ISSUE TITLE
LICENSE/COPYING file missing from repository and pypi sources

### ISSUE THREAD

**Issue by decathorpe** [sdispater/pastel#5]
I'm working on packaging this project for fedora, and during the review, it was pointed out that the repository and the sources that are available from PyPI don't include a COPYING / LICENSE file - which they apparently should to comply with rules for MIT-licensed projects.

**Comment by Conan-Kudo** [comment]
@sdispater ping? This is still an issue...

**Comment by Conan-Kudo** [comment]
@sdispater To give you an idea of why we need this, there are dozens of MIT license variants. So we need a license file that declares _which_ MIT license variant you're using.

**Comment by eli-schwartz** [comment]
This is also a blocker for packaging in Arch Linux.

**Comment by eli-schwartz** [comment]
Any update on clarifying the license terms?

**Comment by eli-schwartz** [comment]
@decathorpe @Conan-Kudo in commit 29d47494e72f9a2f428772ef8758f59656f857db a license file was added. I guess this can be closed now. :)

**Comment by decathorpe** [comment]
Yes! Thanks.
